### ISSUE TITLE
Gatsby Plugin indexing

### ISSUE THREAD

**Issue by RobinCsl** [Jedidiah/gatsby-source-twitch#2]
Hello 👋 

It looks like the previous [PR](https://github.com/Jedidiah/gatsby-source-twitch/pull/1) adding `gatsby-plugin` keyword to the `package.json` file has not been published on NPM as the keyword is not appearing on https://www.npmjs.com/package/gatsby-source-twitch 

Could you please publish a patch version so that it features on the NPM registry too? If I can help in any way, let me know 🙂 

This is part of https://github.com/gatsbyjs/gatsby/issues/14013

Thank you very much!

**Comment by KyleAMathews** [comment]
This would be great 🙏

**Comment by Jedidiah** [comment]
Published this and the Soundcloud plugin to NPM! Thanks @RobinCsl, sorry I missed that.
Should have some update for them both next month too.

**Comment by RobinCsl** [comment]
Awesome, thank you very much @Jedidiah! 🥇
Looking forward to the updates next month!
